### ISSUE TITLE
LOG_LEVELS issue in latest docker image

### ISSUE THREAD

**Issue by vertoforce** [open-webui/pipelines#501]
The latest version of docker image seems to have the following error

```
...
pipelines  |   File "/app/main.py", line 44, in <module>
pipelines  |     logging.basicConfig(level=LOG_LEVELS[log_level])
pipelines  |                               ^^^^^^^^^^
pipelines  | NameError: name 'LOG_LEVELS' is not defined
```

Docker compose:
```yml
  pipelines:
    image: ghcr.io/open-webui/pipelines:main
    container_name: pipelines
    ports:
      - "9099:9099"
    volumes:
      - ./pipelines:/app/pipelines
    restart: always
```

Reverting to `git-cf57fd0` seems to be a workaround for now.
