### ISSUE TITLE
No module named 'llama_index'

### ISSUE THREAD

**Issue by avianinc** [open-webui/pipelines#58]
When I try and Install a pipline in open-webui from a Github URL I get the error ```No module named 'llama_index'```. 

Its interesting to note that when I try and add the pipeline docker image to a docker compose file I recieve the same error during the build and the container will not start. Here is the log output.

```text
INFO:     Started server process [7]
pipelines-1    | INFO:     Waiting for application startup.
pipelines-1    | ERROR:    Traceback (most recent call last):
pipelines-1    |   File "/usr/local/lib/python3.11/site-packages/starlette/routing.py", line 732, in lifespan
pipelines-1    |     async with self.lifespan_context(app) as maybe_state:
pipelines-1    |   File "/usr/local/lib/python3.11/contextlib.py", line 210, in __aenter__
pipelines-1    |     return await anext(self.gen)
pipelines-1    |            ^^^^^^^^^^^^^^^^^^^^^
pipelines-1    |   File "/app/main.py", line 210, in lifespan
pipelines-1    |     await on_startup()
pipelines-1    |   File "/app/main.py", line 189, in on_startup
pipelines-1    |     await module.on_startup()
pipelines-1    |   File "/app/./pipelines/llamaindex_ollama_github_pipeline.py", line 23, in on_startup
pipelines-1    |     from llama_index.embeddings.ollama import OllamaEmbedding
pipelines-1    | ModuleNotFoundError: No module named 'llama_index'
```

If I run the docker compose with just ollama and open-webui images the compose starts fine. I can then run the pipelines as an individial container and runs. I can add the pipelines containter address to the OpenAPI URL and it sees it.. 

Any thoughts?

Here is the compose file that does not work

```text
services:
  ollama:
    image: ollama/ollama:latest
    deploy:
      resources:
        reservations:
          devices:
            - capabilities: [gpu]
    environment:
      - NVIDIA_VISIBLE_DEVICES=all
      - NVIDIA_DRIVER_CAPABILITIES=compute,utility
    volumes:
      - ollama:/root/.ollama
    ports:
      - "11434:11434"
    runtime: nvidia

  open_web_ui:
    image: dyrnq/open-webui
    deploy:
      resources:
        reservations:
          devices:
            - capabilities: [gpu]
    environment:
      - NVIDIA_VISIBLE_DEVICES=all
      - NVIDIA_DRIVER_CAPABILITIES=compute,utility
    volumes:
      - open-webui:/app/backend/data
    ports:
      - "3000:8080"
    extra_hosts:
      - "host.docker.internal:host-gateway"
    restart: always
    runtime: nvidia

  pipelines:
    image: ghcr.io/open-webui/pipelines:main
    deploy:
      resources:
        limits:
          memory: 4g
          cpus: '2.0'
        reservations:
          devices:
            - capabilities: [gpu]
    environment:
      - NVIDIA_VISIBLE_DEVICES=all
      - NVIDIA_DRIVER_CAPABILITIES=compute,utility
    volumes:
      - pipelines:/app/pipelines
    ports:
      - "9099:9099"
    extra_hosts:
      - "host.docker.internal:host-gateway"
    restart: always
    runtime: nvidia

volumes:
  ollama:
  open-webui:
  pipelines:
```

**Comment by justinh-rahb** [comment]
For _reasons_ the UI pipeline installer from URL does not run the installation of dependencies. You should use the envvar `PIPELINES_URLS` in your compose/`docker run` to make sure that pipelines with additional depends will work:
```yaml
  pipelines:
    image: ghcr.io/open-webui/pipelines:main
    deploy:
      resources:
        limits:
          memory: 4g
          cpus: '2.0'
        reservations:
          devices:
            - capabilities: [gpu]
    environment:
      - NVIDIA_VISIBLE_DEVICES=all
      - NVIDIA_DRIVER_CAPABILITIES=compute,utility
      - PIPELINES_URLS="https://raw.githubusercontent.com/open-webui/pipelines/main/examples/pipelines/rag/llamaindex_ollama_github_pipeline.py"
    volumes:
      - pipelines:/app/pipelines
    ports:
      - "9099:9099"
    extra_hosts:
      - "host.docker.internal:host-gateway"
    restart: always
    runtime: nvidia
```
